version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Looser1997$
      MYSQL_DATABASE: url_shortner

  auth_svc:
    image: url-shortner:latest
    build:
      context: .
      dockerfile: AuthDockerfile
    volumes:
      - ./internal:/app
      - ./db:/app/db
    working_dir: /app
    ports:
      - "8090:8090"
      - "8080:8080"
    environment:
      MYSQL_ADDR: mysql  # Use the service name as the MySQL address
      MYSQL_USER: root
      MYSQL_PASSWORD: Looser1997$$
      MYSQL_DATABASE: url_shortner
      BASE_URL : http://localhost:8090/api/v1/redirect/
      PORT: 8090
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

