// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/jmoiron/sqlx"
	"login_api/internal/common/logs"
	"login_api/internal/common/config"
	"login_api/internal/auth/app"
	"login_api/internal/auth/domain"
	"login_api/internal/auth/repository/adapters"
)

// Injectors from wire.go:

func InitializeDomain(config2 config.Config, db *sqlx.DB) (app.PingApp, error) {
	entry := logs.Init(config2)
	mySQLPingRepository := adapters.NewMySQLPINGRepository(db, entry, config2)
	pingDomain := domain.NewPingDomain(entry, config2, mySQLPingRepository)
	pingApplication := app.NewPingApplication(entry, config2, pingDomain)
	return pingApplication, nil
}

func InitializePingApplication(config2 config.Config, db *sqlx.DB) (app.PingApp, error) {
	entry := logs.Init(config2)
	mySQLPingRepository := adapters.NewMySQLPINGRepository(db, entry, config2)
	pingDomain := domain.NewPingDomain(entry, config2, mySQLPingRepository)
	pingApplication := app.NewPingApplication(entry, config2, pingDomain)
	return pingApplication, nil
}

