// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/jmoiron/sqlx"
	"login_api/internal/communication_svc/app"
	"login_api/internal/communication_svc/domain"
	"login_api/internal/communication_svc/repository/adapters"
	"login_api/internal/common/config"
	"login_api/internal/common/logs"
)

// Injectors from wire.go:

func InitializeDomain(config2 config.Config, db *sqlx.DB) (app.PingApp, error) {
	entry := logs.Init(config2)
	postgressPingRepository := adapters.NewPostgressPingRepository(db, entry, config2)
	pingDomain := domain.NewPingDomain(entry, config2, postgressPingRepository)
	pingApplication := app.NewPingApplication(entry, config2, pingDomain)
	return pingApplication, nil
}

func InitializePingApplication(config2 config.Config, db *sqlx.DB) (app.PingApp, error) {
	entry := logs.Init(config2)
	postgressPingRepository := adapters.NewPostgressPingRepository(db, entry, config2)
	pingDomain := domain.NewPingDomain(entry, config2, postgressPingRepository)
	pingApplication := app.NewPingApplication(entry, config2, pingDomain)
	return pingApplication, nil
}

func InitializeCommunicationApplication(config2 config.Config, db *sqlx.DB) (app.CommunicationApp, error) {
	entry := logs.Init(config2)
	postgresAuthRepository := adapters.NewPostgresCommunicationRepository(db, entry, config2)
	communicationDomain := domain.NewCommunicationDomain(entry, config2, postgresAuthRepository)
	communicationApplication := app.NewCommunicationApplication(entry, config2, communicationDomain)
	return communicationApplication, nil
}
